openapi: 3.0.3
info:
  title: cargotracker
  description: cargotracker
  termsOfService: https://github.com/flowck/cargotracker_ddd_golang
  contact:
    email: firmino.changani@gmail.com
  license:
    name: MIT
    url: https://github.com/flowck/cargotracker_ddd_golang/LICENSE.md
  version: 0.0.1
externalDocs:
  description: https://github.com/flowck/cargotracker_ddd_golang/README.md
  url: https://github.com/flowck/cargotracker_ddd_golang
servers:
  - url: http://localhost:3000
  - url: http://localhost:3100
paths:
components:
  schemas:
    GenericResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: A description about the error
        code:
          type: string
          description: Error custom error code such as 'email_in_use'
  responses:
    UnauthorizedError:
      description: 'Usually causes by an authentication token missing'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    DefaultSuccess:
      description: 'Default message when an operation succeeds'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericResponse'
    DefaultError:
      description: 'A generic error response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT